[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "v1.6.1"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.0"

[[constraint]]
  name = "github.com/markbates/refresh"
  version = "1.3.3"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"
