package migrations

// This is an AUTOGENERATED file, if you edit it, you will loose your changes

import (
	"github.com/kiasaki/weeb"
)

var migrations = []*weeb.Migration{}

func migration(id string, upFn, downFn func(*weeb.App)error) struct{} {
	migrations = append(migrations, &weeb.Migration{ID:id, Up: upFn, Down: downFn})
	return struct{}{}
}

// AddMigrationsToApp adds migrations defined in this package to the given 'App'
func AddMigrationsToApp(app *weeb.App) {
	for _, m := range migrations {
		app.Migrations.Add(m.ID, m.Up, m.Down)
	}
}
