exports.MIME_TYPES = {
  "js": "text/javascript",
  "ico": "image/x-icon",
  "css": "text/css",
  "png": "image/png",
  "jpg": "image/jpeg",
  "wav": "audio/wav",
  "mp3": "audio/mpeg",
  "svg": "image/svg+xml",
  "pdf": "application/pdf",
  "doc": "application/msword",
  "eot": "appliaction/vnd.ms-fontobject",
  "ttf": "aplication/font-sfnt",
  "html": "text/html",
  "json": "application/json",
};
